<a href="https://colab.research.google.com/github/kennjoroges/PythonBasics/blob/master/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
#Constant
name = tf.constant(1)

In [0]:
#Job Role Variable
role = tf.Variable(2)

In [37]:
print(name)

Tensor("Const_1:0", shape=(), dtype=int32)


In [0]:
new_value = tf.add(name,role)

In [0]:
update = tf.assign(role,new_value)

In [0]:
#Initialize variables

init_op = tf.global_variables_initializer()

In [0]:
sess = tf.Session()

In [0]:
sess.run(init_op)

In [43]:
print(sess.run(role))

2


In [44]:
for _ in range(5):
  sess.run(update)
  print(sess.run(role))

3
4
5
6
7


##PlaceHolder

In [0]:
a = tf.placeholder(tf.float32)

In [0]:
b = a*2

In [0]:
result = sess.run(b, feed_dict={a:[3,4,5]})

In [48]:
print(result)

[ 6.  8. 10.]


In [49]:
diction = {a:[[[3,4,5],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]], [[3,4,5],[6,7,8],[9,8,7]]]}

result = sess.run(b, feed_dict =diction)

print(result)

[[[ 6.  8. 10.]
  [ 8. 10. 12.]
  [14. 16. 18.]]

 [[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]]

 [[ 6.  8. 10.]
  [12. 14. 16.]
  [18. 16. 14.]]]


In [0]:
sess.close()